### ISSUE TITLE
Critical bug with memory issue when crawling non html files

### ISSUE THREAD

**Issue by brendanheywood** [central-queensland-uni/moodle-tool_crawler#13]
PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 366838044 bytes) in /var/www/sites/moodle.cqu.edu.au/releases/manual_clone_3/admin/tool/crawler/classes/robot/crawler.php on line 744

The crawler is attempting to parse resources which are not html. eg it is currently getting bogged and throwing a memory error on this url which is a zip file:

This page should automatically redirect. If nothing is happening please use the continue link below. ↗
https://moodle.cqu.edu.au/pluginfile.php/467057/mod_page/content/5/CD%202013%20FMU%20Term%203.zip

We need to parse the http headers first and find out if it html and only then conditionally parse the html.

**Comment by roperto** [comment]
The script is only parsing HTML files, but it allocates the contents at least 3 times for any kind of file.

One in the curl as $raw (headers + content), then again at $this->contents (only contents, where the fatal error above occured), then later again setting $data = $this->contents.

My fix was to not copy the contents to $this->contents (and $data later on) if not an HTML, detecting early through the content-type header and if not HTML.

**Comment by roperto** [comment]
Fixed in release 2016121300 .
