### ISSUE TITLE
Error writing to database

### ISSUE THREAD

**Issue by tigani1993** [central-queensland-uni/moodle-tool_crawler#17]
Hi!

The SQL statements on line 183 and 191 in _crawler/classes/robot/crawler.php_ seem to be incorrect (I'm using MySQL).
After clicking the retry-link of a broken link, I got an database writing error. So i changed the statements and now they look like this:

```
// Mark all nodes that link to this as needing a recrawl.
$DB->execute("UPDATE {tool_crawler_url} u
                         INNER JOIN {tool_crawler_edge} e ON e.a = u.id
                         SET needscrawl = ?,
                                 lastcrawled = null
                         WHERE e.b = ?", array($time, $nodeid));
```
```
// Delete all edges that point to this node.
$DB->execute("DELETE
                          FROM {tool_crawler_edge}
                          WHERE b = ?", array($nodeid));
```

So it works for me. Can you reproduce the problem?

-Max

**Comment by roperto** [comment]
Hi Max,

We use pgsql in our environment, but I our CI tests should have detected the wrong statement for MySQL.

I will test your solution and try to use make a compatible solution for both engines.

Cheers,
Daniel

**Comment by roperto** [comment]
Hi Max,

I could reproduce the problem in MySQL using a regression test, it should be fixed now using your query.

Thank you for your contribution,

Daniel
