### ISSUE TITLE
filter in broken links

### ISSUE THREAD

**Issue by adpe** [central-queensland-uni/moodle-tool_crawler#18]
Hello,

is there any possibiltiy that the robot crawls all courses without set the role to site administrator?
And also in the reports it would be nice if there could be a filter for the error codes? 

Thanks in advance,
Adrian

**Comment by tigani1993** [comment]
Hi Adrian,

there is a role for the robot as described in Step 2 of the documentation:

Import role "Robot" from admin/tool/crawler/roles/robot.xml on
Site administration ► Users ► Permissions ► Define roles ► Add a new role
Add this role to the "Link checker robot" user on
Site administration ► Users ► Permissions ► Assign system roles.

-Max

**Comment by brendanheywood** [comment]
@adpe can you describe what report / filtering you'd like which isn't already there? There is an existing report which shows just the crawl errors

**Comment by adpe** [comment]
@tigani1993 
Thanks four your help, I've skipped that step.

@brendanheywood 
My idea is, because there's such a huge list with many entries, that you can filter by error-codes or general conext like "Courses, Board, Dashbaord or equivalent...". So you get a better overview, but that's not really necessary.

**Comment by brendanheywood** [comment]
Are you aware that there are already reports at the course level?

![image](https://cloud.githubusercontent.com/assets/187449/21787204/fc5db6f0-d71b-11e6-888b-b7e4631ad58d.png)

**Comment by adpe** [comment]
@brendanheywood
Thanks I don't see that it exists on course level. Maybe you can help me with my other problem, that the crawler doesn't go through the whole courses? I have done the stept that @tigani1993 have said before.

**Comment by brendanheywood** [comment]
Re not seeing the course level link, what version of moodle are you on?

The the crawler not seeing the whole course, I'd need a lot more info. But probably the easiest way to debug this is to login as the robot user and confirm you can click around and see what you need to see. Start from the seed url that you have configured and click your way into the course. If you can't see what you need then flips some bits on the permissions as needed until you can.

**Comment by adpe** [comment]
Also I have done the Testing part from the documentation. It's all working fine, 

1. I can acces fine the courses with the bash testing (curl -c /tmp/cookies -v -L --user moodlebot:moodlebot http://your_moodle_website.com/course/view.php?id=3) I've tested different course id's. 
2. I switched also the role in the moodle, and I can acces with the robot user the courses manually.
3. I run the robot task from the CLI and I get different results, 423 queries (with robot role) 5666 queries (as system administrator role).

I can't explain what's the problem. Where you think it's the problem with the permissions?

**Comment by brendanheywood** [comment]
Yeah this sounds purely like a permissions thing, I don't think there is any permissions bug here. When you are testing are you using the 'login as' function? If so I'd avoid that and log in manually as the robot user to double check. In another browser or incognito mode keep working through the permissions and checking stuff, purging caches as you go to make sure, and then test it in the other one until the robot can see everything that you want it to see.

To be clear the robot definitely does not need, and absolutely should not have, the admin role. I'd say you might need to see hidden courses, or maybe it can't see the course categories or something. I can't see without looking at your moodle.

There isn't really much more I can do here unless you find an actual bug and can show a reduced test case so I can reproduce it. If you need more commercial support please contact us via https://www.catalyst-au.net/contact-us

**Comment by joelschmid91** [comment]
Hey guys, 
I had the same problem @adpe had, in my case it was because all course categories were hidden. This means the crawler was never able to go into a course as there is no link, except the ones he was enrolled in. Is there any solution to that? 
It would be great if the crawler would go through all courses using the database as a source of information?

**Comment by joelschmid91** [comment]
Okay, so I was able to reproduce the behaviour @adpe had. The problem is because all courses are in course categories which are hidden. If I unhide all course categories the crawler goes through all courses without a problem. 
Enabling the capability: moodle/category:viewhiddencategories **does not** solve the problem. Do you guys have any other idea, how this could be solved without having to unhide all course categories?

**Comment by brendanheywood** [comment]
I'd prefer to open a new clean issue if required. But in your case I still suspect that it's a permissions thing. Can you login manually (not login-as) as the robot user and click around into the courses and categories you need to index? If not, then it's a permissions bug outside of this plugin. If may be another additional capability. If yes then it's a bug in the crawler, or there is some config which means it is ignoring those links. If the latter please open a new issue with details
