### ISSUE TITLE
Site policy stops bot working?

### ISSUE THREAD

**Issue by daveyboond** [central-queensland-uni/moodle-tool_crawler#28]
Hello all,
I have this installed on my server but there is a site policy URL that all users have to confirm before getting access. This seems to be holding up the bot, because the Robot Status page says:

Bot test page was redirected to https://[server]/user/policy.php

I have tried the following:
* "Login as" robot and accept policy
* Change robot account to manual, actually log in as robot, to check site policy accepted, change back to Basic Auth
* Move Basic Auth to the top of the list of authentication methods

None of those have any effect.

Anyone have any ideas?

Best wishes
Steve

**Comment by brendanheywood** [comment]
That's weird, the robot is just a normal user so either of the first two things you tried should have worked.

Have you tested it with the sitepolicy off and confirmed the bot is being correctly logged in using basic auth and it's not being auto logged in as a guest?

You can test this manually with curl:

https://github.com/central-queensland-uni/moodle-tool_crawler#test-basic-authentication-with-curl

**Comment by daveyboond** [comment]
It gets weirder. The curl test seems to work fine - I don't see "you are logged in as" in the output, but it does seem to be working (see output below), and I can see the HTML of the lowest-ID course on my site.

Guest login turned off. Next step was to remove site policy URL - this indeed fixed things, and the bot started working. But I need my site policy, so I turned it back on, and the bot duly stopped working again.

Baffled!

* Server auth using Basic with user 'moodlebot'
> GET /course/view.php?id=3 HTTP/1.1
> Host: emfss.elearning.london.ac.uk
> Authorization: Basic bW9vZGxlYm90Om1vb2RsZWJvdA==
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK

**Comment by brendanheywood** [comment]
If you don't see 'you are logged in as' in the html then something probably still isn't right, and I suspect it's still something to do with guest mode which is multi layered and non trivial. Do you have guess access on at the site level but turned off at the course enrolment level?

**Comment by daveyboond** [comment]
Well it's definitely working OK now, and guest mode is defiinitely off, so I don't know. Maybe that string was there and I missed it.

**Comment by brendanheywood** [comment]
ok cool, any future dramas please open a new issue

**Comment by nicoroeser** [comment]
Related to #5.

**Comment by nicoroeser** [comment]
We are hitting this issue on new `tool_crawler` installations where we manually add the bot user. After manually logging in as the bot user and accepting the site terms, the crawler works.

In my opinion, adding a short note about this to `README.md` would be a good solution. Alternatively/additionally, the bot user creation procedure could/should auto-accept the site terms (in `classes/tool/crawler.php`, function `auto_create_bot`).

The reason that manually accepting the site policy sometimes seems not to work is that the fact that the site policy needs to be agreed to is stored in the session. If the bot user has an open session, the problem will occur. We found that a suitable workaround is to remove the cookie jar file after the site policy has been accepted.

**Comment by brendanheywood** [comment]
I think this is best covered in the readme as every site is different and various site have different hoops to jump through for new users. I don't think it's feasible to automatically cover all the use cases here. Are you able to make a pr for the readme?
