### ISSUE TITLE
Coding error detected, it must be fixed by a programmer: PHP catchable fatal error

### ISSUE THREAD

**Issue by jb-fol** [central-queensland-uni/moodle-tool_crawler#3]
I narrowed this plugin down to causing a fatal error in a completely different area of Moodle. In Site Admin > Plugins > Activity Modules > Glossary, there is the option to edit and hide/show Display formats. Both the update and hide/show icons result in the message "Coding error detected, it must be fixed by a programmer: PHP catchable fatal error". I uninstalled all my additional plugins, one by one, and this one was the only one that caused this error. No idea why, I’m not a developer, but happy to test it / replicate it if needed.

Moodle 3.1+ (Build: 20160616)
php5/apache2
mysql (5.5.47-0+deb6u1)

**Comment by brendanheywood** [comment]
thanks, can you provide some more detail to reproduce this, eg do you need to create a page which uses a glossary term and its when crawling that page when it exploded?

**Comment by jb-fol** [comment]
No, I've just installed it on another site which is not using Glossaries and got the same problem so I don’t think it’s a crawling error as such.

So to reproduce...

Without the link crawler installed...
1. Go to Site Admin > Plugins > Activity Modules > Glossary
2. At the bottom of that page is the option to edit and hide/show Display formats.
3. Click on the Update icon (cog) and the 'update settings' page will display,
     or Click on the hide/show icon (eye) and it will do the requested action.

Now with the link crawler installed...
Repeat the three steps and you will get the message "Coding error detected, it must be fixed by a programmer: PHP catchable fatal error".

Debugging shows:
Error code: codingerror
Stack trace:
line 60 of /admin/tool/crawler/settings.php: call to require()

**Comment by jb-fol** [comment]
Sorry, should have said that my latest test was running Moodle 3.0.3+ (Build: 20160317) and the original was on Moodle 3.1+ (Build: 20160616). Both are on php5/apache2 with mysql (5.5.47-0+deb6u1).

**Comment by brendanheywood** [comment]
hi @jb-fol, I've fixed the file require bug, thanks!
