### ISSUE TITLE
Permission issue results in php notice.

### ISSUE THREAD

**Issue by joelschmid91** [central-queensland-uni/moodle-tool_crawler#4]
Hello

I just installed auth_basic and the moodle-tool_crawler on Moodle 3.1. Having debugging enabled, the admin/tool/crawler/index.php page results in the following Notice:

> PHP Notice:  Undefined offset: 2 in /var/www/html/moodle-dev/admin/tool/crawler/classes/robot/crawler.php on line 708, referer: https://url.com/admin/tool/crawler/report.php?report=queued

If I var_dump the $header and $headersize variable before line 708 I get a bool(false) or a 0... 

I guess this is a permission issue as the bot is not able to request the test page. I created the user automatically and gave him even Site-Administration Permissions to check if the error would disappear, but it didn't. What am I doing wrong?

**Comment by brendanheywood** [comment]
Do you see that error in the gui when logged in as an admin, or when the crawler is doing it's thing?

Can you manually do a crawl from the cli and dump the whole command and the output +error please? eg 

php cli/crawl-as.php -u=http://example.com

**Comment by brendanheywood** [comment]
Also if you turn on the logging in the auth_basic plugin and give me the logs for that while it is trying to crawl too please

**Comment by joelschmid91** [comment]
Running the crawl-as.php command I get the following error:
`Error: Bot could not request test page[root@servername crawler]# php cli/crawl-as.php -u=https://mymoodle.domain.com
string(62) "https://mymoodle.domain.com/admin/tool/crawler/tests/test1.php"
PHP Notice:  Undefined offset: 2 in /var/www/html/moodle-dev/admin/tool/crawler/classes/robot/crawler.php on line 708

Notice: Undefined offset: 2 in /var/www/html/moodle-dev/admin/tool/crawler/classes/robot/crawler.php on line 708
Error: Bot could not request test page`

Logging is enabled but I can't find the logs, where do I have to look?

**Comment by brendanheywood** [comment]
So curl is failing, I've added some better error detection so now you should at least get a meaningful error message. I also had an issue with self sign certs failing which I have fixed which could have been the root cause in your particular case too. Can you please pull and see if that's fixed it?

**Comment by joelschmid91** [comment]
Awesome, the error is gone! I guess it was due to the self signed certificate. Thank you for your fast help!

**Comment by brendanheywood** [comment]
Great stuff, thanks for the bug report!
