### ISSUE TITLE
Bot test page was redirected to http://localhost:8084/user/policy.php

### ISSUE THREAD

**Issue by gregersen12** [central-queensland-uni/moodle-tool_crawler#5]
In installing and testing this plugin I came across an issue that I can't seem to figure out how to bypass. 

We enforce users to read our policy upon signup, so the bot gets redirected to our userpolicy page.

That results in the string "Bot test page was redirected to http://localhost:8084/user/policy.php"
rather than 'Good' on Robot Status Page.
Is there a way to circumvent this?

![image](https://cloud.githubusercontent.com/assets/9022499/19148937/7fa3e500-8bbf-11e6-8155-a3525dd1e265.png)

Furthermore: Running the curl auth test, I get "You are logged in as guest". I feel like I should be logged in as the user I specified login information for.
However, running the same command with my own login-credentials I also get "You are logged in as guest". 
It could be useful information.

ALSO: Running the task as cli itself, does bring output similar to what's described in the readme.
However, I am worried I might be running sort of a "limited edition" here :-)

**Comment by brendanheywood** [comment]
Log in normally and manually as the bot user and agree to the policy and then move on.

The guest login feels like a separate bug, have you properly installed and configure the basic auth, and importantly have you made the basic auth the first auth plugin in the list?

Try doing a cli curl test and turn on debugging in side the basic auth plugin and it will emit extra headers to help debug what is going on like this:

![image](https://cloud.githubusercontent.com/assets/187449/19149763/45579b1c-8c0f-11e6-9276-603fbef3f517.png)

**Comment by gregersen12** [comment]
Hey Brendan,

That almost seemed overly simple.
The missing piece was moving auth_basic to the top of the list. 
I don't understand that part of moodle but that seemed to do it: I am now getting the 'Good' status.

Thanks!

**Comment by brendanheywood** [comment]
Another happy customer :)
