### ISSUE TITLE
Error reading from database

### ISSUE THREAD

**Issue by JensReineking** [central-queensland-uni/moodle-tool_crawler#6]
Hi.
I tried installing the crawler and got the error message below.
The only thing I think I did not do according to the documentation is installing the crawler via the repository and not via github (since so far I don't know how).
Can you help me?

Thanks in advance,
Jens

**Debug info: Table 'moodle_bkuda.mdl_tool_crawler_url' doesn't exist**

SELECT COUNT(*)
FROM mdl_tool_crawler_url b
JOIN mdl_tool_crawler_edge l ON l.b = b.id
WHERE b.httpcode != '200'
[array (
)]
Error code: dmlreadexception 

**Stack trace:**
-     line 474 of /lib/dml/moodle_database.php: dml_read_exception thrown
-     line 1088 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
-     line 1527 of /lib/dml/moodle_database.php: call to mysqli_native_moodle_database->get_records_sql()
-     line 1600 of /lib/dml/moodle_database.php: call to moodle_database->get_record_sql()
-     line 392 of /admin/tool/crawler/classes/robot/crawler.php: call to moodle_database->get_field_sql()
-     line 53 of /admin/tool/crawler/index.php: call to tool_crawler\robot\crawler->get_pages_withbroken_links()

**Comment by brendanheywood** [comment]
Can you confirm you ran the upgrade script either from the GUI or the command line? This just looks like it was installed completely

**Comment by JensReineking** [comment]
I ran everything from the GUI inside moodle.

**Comment by brendanheywood** [comment]
That's really weird, can you jump into the database and see whether it is just that one table missing, or are all the  tool_crawler_* tables missing?

**Comment by JensReineking** [comment]
I'll figure out how to view the database itself and then have a look.
Could be a few days - this is very new to me (also: other work).

**Comment by brendanheywood** [comment]
If you have any more feedback please re-open this issue, thanks
