### ISSUE TITLE
Automatic emails for broken links

### ISSUE THREAD

**Issue by gregersen12** [central-queensland-uni/moodle-tool_crawler#7]
Heya.

I am wondering if it is possible to set up the plugin in a way, that it will automatically send out mails to inform the (some) user, if links are broken and need attention.

I am wondering if it is as simple as adding an email adress to the user that acts the link crawler robot.

Or is this simply not an implemented feature?

**Comment by brendanheywood** [comment]
No sorry this isn't an implemented feature. On the site this was built for the scale of the data that wouldn't really be a viable solution, you'd want to email the manager of the course that contained the links. 

Something like what you want could be set up very easily using this plugin:

https://moodle.org/plugins/report_customsql
