### ISSUE TITLE
Add an option to clear the crawler history and url list.

### ISSUE THREAD

**Issue by nhoobin** [central-queensland-uni/moodle-tool_crawler#9]
If the filtering was not set up correctly then the crawler may possibly have an enormous list of urls to process.

Lets add a button to clean the crawler tables and a reset the configuration.

We way want to keep the statistics.

**Comment by nhoobin** [comment]
A cli script exists for this purpose.
admin/tool/crawler/reset.php

**Comment by brendanheywood** [comment]
No gui? Increasingly in the lands docker and friends cli access is more of a pain, I'd want a gui too please
